services:
  etd-frontend:
    build: ./etd-next     # path to your Next.js folder
    container_name: etd-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - etd-backend

  etd-backend:
    build: ./etd-backend
    container_name: etd-backend
    restart: always
    ports:
      - "3836:3836"
    depends_on:
      - etd-db
      - etd-redis

  etd-db:
    image: postgis/postgis
    container_name: etd-db
    restart: always
    env_file:
      - ./etd-backend/_database.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - etd-network

  etd-redis:
    image: bitnami/redis:latest
    container_name: etd-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - etd-network

networks:
  etd-network:

volumes:
  postgres-data:
